### ISSUE TITLE
Support CILogon with Auth0

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#65] opened 2020-10-12 21:44 UTC
If we supported CILogon (https://github.com/cilogon) with our Auth0 setup, then we would be able to connect to the login infrastructure of many more academic institutions. 

This should be possible via: https://www.cilogon.org/auth0

**Comment by choldgraf** [comment] 2020-10-21 16:36
Note that CILogon will only work with organizations that use eduroam. Wageningen might be a good candidate to test this out (https://www.wur.nl/en/Value-Creation-Cooperation/Facilities/Mobile-Device-Support/You-work-or-study-at-an-Eduroam-participant-and-you-bring-your-own-laptop.htm)

**Comment by yuvipanda** [comment] 2021-08-23 09:12
Closing as dupe of https://github.com/2i2c-org/pilot-hubs/issues/315

**Closed by yuvipanda** 2021-08-23 09:12 UTC
Labels: type: enhancement
