### ISSUE TITLE
Pangeo Staging hub can't launch sessions from some profiles

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#660] opened 2021-09-06 17:38 UTC
### Description

On the Pangeo hub, some of the profiles do not correctly launch. For example, clicking the "micro" profile at the top results in a hang, and these error messages:

<img width="635" alt="chrome_rbMC9KmpML" src="https://user-images.githubusercontent.com/1839645/132249611-f80eb01b-b6ac-48a9-89ce-10893eed87f1.png">

### Value / benefit

This seems important since many students will see this profile list when logging in, and if they don't click the right one they'll just get an error right now.

**Comment by damianavila** [comment] 2021-09-07 13:00
I think #661 is a dupe of this one, but it has more details, so closing this one now.

**Closed by damianavila** 2021-09-07 13:00 UTC
Labels: type: bug, :label: pangeo
