### ISSUE TITLE
[BUG] Grafana dashboards for COESSING hub not showing any activity

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/pilot-hubs#555] opened 2021-07-27 09:51 UTC
# Summary

The grafana charts for the COESSING hub are not showing data for active users despite @paigem confirming that there has been activity over the last day of the live workshop

<img width="1848" alt="Screenshot 2021-07-27 at 10 47 47" src="https://user-images.githubusercontent.com/44771837/127134012-d5c708a0-888f-4257-bf10-c69c6dd662a9.png">

# Expected Behaviour

The grafana charts would reflect the usage over the last day

**Comment by paigem** [comment] 2021-07-30 02:06
Any progress here @sgibson91? It would be nice to see some usage statistics for the COESSING hub. Thanks!

**Comment by choldgraf** [comment] 2021-07-30 13:49
@paigem we haven't figured it out yet, sorry! still trying to understand where the lack of data is coming from.

**Comment by yuvipanda** [comment] 2021-07-30 18:46
I'm fairly certain this is caused by https://github.com/jupyterhub/grafana-dashboards/issues/30.

I've very temporarily made a copy of the default cluster dashboard and changed just the 'running user' graph to account for the missing labels. You can see that here: https://grafana.pangeo.2i2c.cloud/d/5wL3ZeW7k/cluster-information-no-labels?viewPanel=3&orgId=1&from=now-2d&to=now.

https://github.com/jupyterhub/grafana-dashboards/issues/30 needs to be fixed though, as it'll affect all our dashboards

**Comment by choldgraf** [comment] 2021-08-17 21:15
@paigem in case you didn't see the grafana plot that @yuvipanda shared here's an image:

![image](https://user-images.githubusercontent.com/1839645/129801526-f0949afa-f12b-41e7-a3da-a9a29c368ef8.png)

It looks like you topped out around 17 simultaneous users and got some consistent usage for each day of the workshop. Here's a link to the dashboard:

https://grafana.pangeo.2i2c.cloud/d/5wL3ZeW7k/cluster-information-no-labels?orgId=1&from=1626937571612&to=1628145428673&viewPanel=3

I'm gonna close this issue so that we can track the long-term fix for this in https://github.com/jupyterhub/grafana-dashboards/issues/30

**Closed by choldgraf** 2021-08-17 21:15 UTC
Labels: type: bug
