### ISSUE TITLE
Allow hubs to maintain their own user image

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#493] opened 2021-06-30 17:38 UTC
For most of the hubs hosted on our cluster (in *.pilot.2i2c.cloud, and *.cloudbank.2i2c.cloud), we use [this user image](https://github.com/2i2c-org/pilot-hubs/tree/master/images/user). This is a bit generic, and has things many people want. But customizing this on a per-hub basis doesn't work very well!

1. Version conflicts will happen quickly and cause big problems
2. Any environment updates require intervention from 2i2c engineers
3. If we install additional languages, becomes confusing for users of hubs that don't need it.

So we need a solution that's as close to binder as possible, in terms of *empowring our hub admins*. It should:

1. Give hub admins complete control over the user environment
2. ... in a way that lets them iterate and test the environment with standard tools (in this case, mybinder.org)
3. ... without having to deeply understand how all the pieces (repo2docker, docker, mybinder, binderhub, jupyterhub, etc) fit together
4. ... with minimal intervention from 2i2c staff.

## Potential solution

For the [peddie hub](https://peddie.pilot.2i2c.cloud), @sawula requested the [py5](https://py5.ixora.io/) package. This adds a new kernel, and also requires Java. Instead of adding it to default image, I've instead:

- Forked the binderized [example repo](https://github.com/hx2A/py5examples) to https://github.com/2i2c-org/peddie-image (Thanks to https://github.com/2i2c-org/pilot-hubs/issues/479#issuecomment-866519098)
- Setup [repo2docker-action](https://github.com/jupyterhub/repo2docker-action#push-image-to-quayio) to push to our quay.io account
- Setup a [different action](https://github.com/2i2c-org/peddie-image/blob/main/.github/workflows/binder.yaml) to comment with a 'test this in binder' link for each PR
- [Add docs](https://github.com/2i2c-org/peddie-image#making-a-change) on how to update your hub to use a new image + tag with the [JupyterHub Configurator](https://pilot.2i2c.org/en/latest/admin/howto/configurator.html)

There's lots to be improved here, but I think this is a good start on making this process easier.

Related: https://github.com/2i2c-org/pilot-hubs/issues/312

**Comment by yuvipanda** [comment] 2021-06-30 17:40
Pre-existing very helpful feedback about the configurator: https://github.com/2i2c-org/pilot-hubs/pull/329#issuecomment-809747595

**Comment by damianavila** [comment] 2021-07-02 13:40
This is great @yuvipanda!
I really like the idea "test this in binder"... it is super important the users do not need to deal with local setups to test their changes.
Maybe one future improvement would be a way to automatically update the image from the very same image repository, so they do not need to go through the configurator step... although the configurator path is more than enough for now, IMHO.

**Comment by choldgraf** [comment] 2021-08-31 03:07
Could we consider this a duplicate of https://github.com/2i2c-org/pilot-hubs/issues/631 ?

**Comment by GeorgianaElena** [comment] 2021-09-03 14:29
@choldgraf, I opened [an issue](https://github.com/2i2c-org/hub-user-image-template/issues/2) about the `test this in binder` feature in the [new user image template repository](https://github.com/2i2c-org/hub-user-image-template).

I think this was the only thing was missing from https://github.com/2i2c-org/pilot-hubs/issues/631. So, I think we could potentially close this one and leave the other issue open (since it's is more "closer" to where the change should happen).

What do you all think?

**Comment by choldgraf** [comment] 2021-09-03 19:44
perfect - that makes sense to me! let's close this and track it in #631 thanks Georgiana :-)

**Closed by choldgraf** 2021-09-03 19:44 UTC
Labels: type: enhancement, :label: environment, :label: feature
